import Link from "next/link";
import { BrandImage } from "./brand-image";
import { ArticleCard } from "./client-components";
import { ArrowIcon, ConsultationBanner, SectionHeading, ServiceCard } from "./site-components";
import { articles, brand, primaryServices, testimonials, whatsappLink } from "./site-data";

const processSteps = [
  { title: "Entendemos o contexto", description: "Você explica sua situação e informa quais documentos ou decisões estão envolvidos." },
  { title: "Analisamos as possibilidades", description: "A demanda é avaliada com atenção aos riscos, aos documentos e às alternativas disponíveis." },
  { title: "Definimos os próximos passos", description: "Você recebe orientação clara para compreender a estratégia e os encaminhamentos do caso." },
];

export default function Home() {
  return (
    <main id="conteudo-principal">
      <section aria-labelledby="hero-title" className="home-hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow hero-eyebrow"><span aria-hidden="true" className="hero-eyebrow-dot" />Advocacia em Itajaí · {brand.oab}</p><h1 id="hero-title">Seu patrimônio merece uma <span>estratégia à altura.</span></h1><p className="hero-description">Direito imobiliário, empresarial e civil com atendimento próximo, análise responsável e orientação clara para as decisões que realmente importam.</p><div aria-label="Principais áreas de atuação" className="hero-specialties"><span>Imobiliário</span><span>Empresarial</span><span>Cível</span></div><div className="hero-actions"><a className="button button-accent" href={whatsappLink()}>Agendar atendimento <ArrowIcon /></a><Link className="button button-text-light" href="/atuacao/">Conheça nossas áreas <ArrowIcon /></Link></div><div className="hero-location"><span aria-hidden="true" className="availability-dot" />Atendimento presencial em Itajaí e online para todo o Brasil</div></div><div className="hero-portrait-wrap"><div className="portrait-frame"><BrandImage alt="Dr. Fabiano Odilon Rebelo, advogado em Itajaí inscrito na OAB/SC 68.648" className="hero-portrait" decoding="async" fetchPriority="high" height={735} loading="eager" src={brand.portrait} width={718} /><div className="portrait-caption"><span>Dr. Fabiano Odilon Rebelo</span><span>{brand.oab}</span></div></div><div aria-hidden="true" className="hero-credential"><span>Atendimento jurídico</span><strong>Itajaí · SC</strong></div><p aria-hidden="true" className="hero-vertical-note">Clareza · Técnica · Responsabilidade</p></div></div></section>
      <section aria-label="Informações do escritório" className="trust-strip"><div className="container trust-grid"><div><span className="trust-label">Advogado responsável</span><strong>Fabiano Odilon Rebelo</strong></div><div><span className="trust-label">Inscrição profissional</span><strong>{brand.oab}</strong></div><div><span className="trust-label">Atendimento presencial</span><strong>Itajaí, Santa Catarina</strong></div><div><span className="trust-label">Formatos de consulta</span><strong>Presencial, online e in-company</strong></div></div></section>
      <section className="section practice-section"><div className="container"><div className="section-heading-row"><SectionHeading description="Orientação jurídica para proteger decisões, organizar responsabilidades e lidar com situações que envolvem seu patrimônio ou sua empresa." eyebrow="Como podemos ajudar" title="Atuação jurídica com direção e clareza." /><Link className="text-link all-services-link" href="/atuacao/">Ver todas as áreas <ArrowIcon /></Link></div><div className="service-grid">{primaryServices.map((service, index) => <ServiceCard index={index} key={service.slug} service={service} />)}</div><p className="practice-other">Também atendemos demandas de <Link href="/atuacao/advogado-usucapiao-itajai/">usucapião</Link>, <Link href="/atuacao/direito-de-familia-itajai/">família</Link>, <Link href="/atuacao/inventario-itajai/">inventários</Link> e <Link href="/atuacao/direito-previdenciario-itajai/">direito previdenciário</Link>.</p></div></section>
      <section className="section about-preview-section"><div className="container about-preview-grid"><div className="about-image-wrap"><BrandImage alt="Advogado Fabiano Odilon Rebelo em seu escritório" className="about-preview-image" decoding="async" height={720} loading="lazy" src={brand.portraitEditorial} width={640} /><div className="about-image-caption"><span>{brand.oab}</span><span>{brand.creci}</span></div></div><div className="about-preview-copy"><p className="eyebrow">Quem está ao seu lado</p><h2>Experiência de mercado. <span>Visão jurídica.</span></h2><p>Fabiano Odilon Rebelo une a vivência no mercado imobiliário à formação em Direito pela Universidade do Vale do Itajaí. Uma combinação importante para compreender documentos, negociações e decisões patrimoniais de forma prática.</p><blockquote>“Grandes decisões exigem mais do que bons conselhos. Exigem respaldo jurídico inquestionável.”</blockquote><Link className="text-link" href="/advogado-odilon-rebelo/">Conheça o advogado <ArrowIcon /></Link></div></div></section>
      <section className="section approach-section"><div className="container"><SectionHeading description="Um atendimento organizado começa por ouvir, compreender o contexto e explicar com objetividade o que pode ser feito." eyebrow="Como funciona o atendimento" title="Sem promessas vazias. Com próximos passos claros." /><div className="process-grid">{processSteps.map((step, index) => <article className="process-step" key={step.title}><span className="process-index">{String(index + 1).padStart(2, "0")}</span><h3>{step.title}</h3><p>{step.description}</p></article>)}</div></div></section>
      <section className="section testimonials-section"><div className="container"><div className="section-heading-row"><SectionHeading eyebrow="Experiências compartilhadas" title="O atendimento, na visão de quem conhece." /><a className="text-link" href={brand.reviewUrl} rel="noopener noreferrer" target="_blank">Ver avaliações no Google <ArrowIcon /></a></div><div className="testimonial-grid">{testimonials.map((testimonial) => <blockquote className="testimonial-card" key={testimonial.name}><span aria-label="Avaliação de cinco estrelas" className="review-stars">★★★★★</span><p>“{testimonial.quote}”</p><footer><strong>{testimonial.name}</strong><span>{testimonial.location}</span></footer></blockquote>)}</div></div></section>
      <section className="section insights-section"><div className="container"><div className="section-heading-row"><SectionHeading description="Conteúdos para entender situações jurídicas com mais contexto e tomar decisões de maneira consciente." eyebrow="Informação que ajuda a decidir" title="Direito explicado de forma direta." /><Link className="text-link" href="/blog/">Explorar todos os artigos <ArrowIcon /></Link></div><div className="article-grid home-article-grid">{[articles[11], articles[0], articles[8]].map((article) => <ArticleCard article={article} key={article.slug} />)}</div></div></section>
      <ConsultationBanner />
    </main>
  );
}
